### ISSUE TITLE
Bug: Haiku is fine, but password repeats 2nd line

### ISSUE THREAD

**Issue by renemarc** [Akashic101/haiku-password-generator#1]
Cute project found through r/selfhosted, thanks!

While the generated Haiku is sound, the final password is a contatenation of the 1st, 2nd, and 2nd line again, instead of the expected 1-2-3.

![image](https://github.com/Akashic101/haiku-password-generator/assets/13276793/d076be6e-d71a-42c6-9a6c-661d172c7ae1)

Tested on Docker using `docker.io/akashic/haiku-password-generator:latest` and on both Firefox 123 and Edge 122.

**Comment by Akashic101** [comment]
Thank you for pointing out the error, I had an unfortunate typo which used the second line twice, it should be fixed now with 9f579ca33b41bc2df3af977ea80a9c0bb897467e. The docker-image has been updated so by updating it on your side it should all be working now
